import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { supabaseAdmin } from "@/utils/supabase/admin";
import { mockDb } from "@/utils/mockDb";

export async function POST(request: Request) {
  try {
    const { full_name, email, phone, password, referral_code } = await request.json();

    if (!full_name || !email || !phone || !password) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    const isMock = !process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL.includes("placeholder");

    let userId = "mock-user-uuid-12345";
    let generatedReferralCode = "SPICEMCK";

    if (!isMock) {
      // 1. Check if referrer exists if code is provided
      let referredBy: string | null = null;
      if (referral_code) {
        const { data: referrer, error: refErr } = await supabaseAdmin
          .from("profiles")
          .select("id")
          .eq("referral_code", referral_code)
          .maybeSingle();

        if (referrer) {
          referredBy = referrer.id;
        }
      }

      // 2. Create Supabase Auth User
      const { data: authUser, error: authErr } = await supabaseAdmin.auth.admin.createUser({
        email,
        password,
        phone: `+91${phone}`,
        email_confirm: true,
        phone_confirm: true,
      });

      if (authErr || !authUser.user) {
        return NextResponse.json({ error: authErr?.message || "Failed to create user in Auth" }, { status: 500 });
      }

      userId = authUser.user.id;

      // 3. Create profile in public.profiles
      // Note: referral_code will be auto-generated by trigger if not supplied, 
      // or we can let the trigger handle it.
      const { data: profile, error: profErr } = await supabaseAdmin
        .from("profiles")
        .insert({
          id: userId,
          full_name,
          email,
          phone,
          email_verified: true,
          phone_verified: true,
          referred_by: referredBy,
        })
        .select("referral_code")
        .single();

      if (profErr) {
        // Rollback user creation on profile failure
        await supabaseAdmin.auth.admin.deleteUser(userId);
        return NextResponse.json({ error: profErr.message || "Failed to create profile record" }, { status: 500 });
      }

      if (profile) {
        generatedReferralCode = profile.referral_code;
      }
    } else {
      // Mock mode: generate a random uuid and save profile
      userId = "usr_" + Math.random().toString(36).substr(2, 9);
      generatedReferralCode = "SPICE" + Math.random().toString(36).substring(2, 5).toUpperCase();
      mockDb.upsertProfile({
        id: userId,
        full_name,
        email,
        phone,
        email_verified: true,
        phone_verified: true,
        role: "customer",
        referral_code: generatedReferralCode,
        referred_by: null,
        total_points: 0,
        discount_tier: "bronze",
        created_at: new Date().toISOString(),
      });
    }

    // 4. Set session cookies (Next.js cookies helper)
    const sessionData = {
      userId,
      fullName: full_name,
      email,
      phone,
      verified: true,
      role: "customer",
      referralCode: generatedReferralCode,
    };

    cookies().set("session", JSON.stringify(sessionData), {
      httpOnly: true,
      secure: process.env.NODE_ENV === "production",
      sameSite: "strict",
      maxAge: 60 * 60 * 24, // 1 day
      path: "/",
    });

    return NextResponse.json({
      success: true,
      userId,
      referralCode: generatedReferralCode,
      message: "Account created and logged in successfully",
    });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
